import "@/styles/app.styles.scss";
export const metadata = {
  title: "Sign In",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>{children}</>
  )
}
